"""Combat system — independent turn controller for COC 7th combat."""
from __future__ import annotations
from dataclasses import dataclass, field
import random
import re
from typing import Any

from .messages import CombatInit, CombatResult
from config import COMBAT_LLM_ENHANCEMENT
from prompts import _show_prompt


# ── Module-level helpers ──

def _roll_damage(damage_spec, STR: int = 50, SIZ: int = 50) -> int:
    """Roll damage from structured spec or legacy string formula.

    新格式 (dict):
        {"dice_n": int, "dice_d": int, "bonus": int, "use_db": bool}
        伤害 = Σ(dice_n × D dice_d) + bonus + DB(if use_db)

    旧格式 (str):  "1D6+DB", "1D10+2", "4D6/2D6/1D6" 等，自动解析。
    """
    from investigator.rules import calc_db

    if damage_spec is None:
        return 0
    if not isinstance(damage_spec, (str, dict)):
        return 0

    # ── 旧格式字符串 → 自动转 dict ──
    if isinstance(damage_spec, str):
        damage_spec = _parse_legacy_damage(damage_spec)

    total = 0

    # base dice
    dice_n = damage_spec.get("dice_n", 0)
    dice_d = damage_spec.get("dice_d", 0)
    if dice_n > 0 and dice_d > 0:
        for _ in range(dice_n):
            total += random.randint(1, dice_d)

    # flat bonus
    total += damage_spec.get("bonus", 0)

    # damage bonus
    if damage_spec.get("use_db", False):
        db = calc_db(STR, SIZ)
        if db.startswith("+"):
            db = db[1:]
        if db.startswith("-"):
            total += int(db)
        elif "D" in db:
            total += _roll_damage(db, STR, SIZ)
        else:
            try:
                total += int(db)
            except ValueError:
                pass

    return max(0, total)


def _parse_legacy_damage(formula: str) -> dict:
    """Convert legacy damage formula string to structured dict. 一次迁移用。"""
    f = formula.replace(" ", "")
    spec = {"dice_n": 0, "dice_d": 0, "bonus": 0, "use_db": False}

    # 散弹枪射程格式
    if "/" in f:
        f = f.split("/")[0].strip()

    parts = f.split("+")
    for part in parts:
        part = part.strip()
        if part == "DB":
            spec["use_db"] = True
        elif "D" in part:
            m = re.match(r"(\d*)D(\d+)", part)
            if m:
                spec["dice_n"] = int(m.group(1)) if m.group(1) else 1
                spec["dice_d"] = int(m.group(2))
        else:
            try:
                spec["bonus"] += int(part)
            except ValueError:
                pass
    return spec


def _apply_armor(damage: int, armor: str) -> int:
    """Reduce damage by armor value. armor like '2点厚皮' -> 2."""
    m = re.search(r"(\d+)", armor)
    reduction = int(m.group(1)) if m else 0
    return max(0, damage - reduction)


def _apply_damage_multiplier(damage: int, damage_type: str, multipliers: dict) -> int:
    """Apply enemy damage multipliers: >1=vuln, <1=resist, 0=immune."""
    mult = multipliers.get(damage_type, 1.0)
    return max(0, int(damage * mult))


# ── Data structures ──

@dataclass
class CombatAction:
    """Record of one combat action (player or enemy)."""
    actor: str = ""           # "player" | enemy instance_id
    action_type: str = ""     # "attack" | "dodge" | "flee" | "special"
    weapon: str = ""
    skill_name: str = ""
    skill_value: int = 0
    roll: int = 0
    tier: str = ""            # fumble|failure|regular|hard|extreme
    target: str = ""
    damage: int = 0
    damage_type: str = "物理"
    hp_before: int = 0
    hp_after: int = 0
    narrative: str = ""
    success: bool = False
    round_num: int = 0


@dataclass
class CombatState:
    """Mutable combat state for one fight."""
    round: int = 1
    enemies: list[Any] = field(default_factory=list)
    player_hp: int = 0
    player_hp_max: int = 0
    player_san: int = 0
    initiative_order: list[str] = field(default_factory=list)
    is_player_turn: bool = True
    finished: bool = False
    log: list[CombatAction] = field(default_factory=list)
    full_log: list[CombatAction] = field(default_factory=list)
    _player_dodging: bool = False
    _player_concealed: bool = False
    _player_aim_counter: int = 0
    _boss_hp_max: int = 0
    _boss_current_phase: str = ""
    _correction_log: list[str] = field(default_factory=list)  # LLM per-round correction narratives


# ── Combat system ──

class CombatSystem:
    """COC 7th simplified combat controller. Independent of Keeper pipeline.

    Receives CombatInit, runs combat loop, returns CombatResult.
    Player actions: fixed options (punch/kick/weapon/dodge/flee).
    Enemy actions: weight-based attack selection, rule-driven targeting.

    llm_enhancement (bool, default from config): when True, per-round narrative
    is generated by LLM via build_combat_narrative_prompt() and the final
    CombatResult.narrative is populated. Currently disabled — plan B (O9).
    """

    def __init__(self, weapon_lib=None, llm_enhancement: bool = COMBAT_LLM_ENHANCEMENT):
        self.weapon_lib = weapon_lib
        self.llm_enhancement = llm_enhancement

    # ── Public API ──

    def run_combat(self, combat_init: CombatInit, player_action: str = "", max_rounds: int = 20) -> CombatResult:
        """Run full combat loop with layered execution: deterministic -> LLM gate -> apply."""
        state = self._init_combat(combat_init)
        player = combat_init.player
        environment_actions = getattr(combat_init, 'environment_actions', [])
        available = self._get_player_actions(player, environment_actions)

        action_id = player_action or combat_init.player_action or "punch"
        if not any(a["id"] == action_id for a in available):
            if action_id == "punch" and not any(a["id"] == "punch" for a in available):
                action_id = available[0]["id"] if available else "punch"

        targets = combat_init.player_targets or []
        player_extra = getattr(combat_init, 'player_extra', '') or ''

        for e in state.enemies:
            if not hasattr(e, 'hp_max') or not getattr(e, 'hp_max', 0):
                e.hp_max = getattr(e, 'hp', 10)
            if getattr(e, 'boss_mechanics', ''):
                state._boss_hp_max = getattr(e, 'hp_max', state.player_hp)

        round_log = []
        needs_llm = self._any_special_rules(combat_init, state.enemies)

        while not state.finished and state.round <= max_rounds:
            alive_enemies = [e for e in state.enemies
                            if getattr(e, 'hp', 1) > 0 and getattr(e, 'status', '') not in ('dead', 'defeated')]
            if not alive_enemies:
                state.finished = True
                break

            round_targets = targets if targets else [alive_enemies[0].instance_id]

            # ── 玩家多轮攻击：根据武器 multi_attack 扩展目标列表 ──
            match = next((a for a in available if a["id"] == action_id), None)
            multi = match.get("multi_attack", 1) if match else 1
            if multi > len(round_targets):
                last = round_targets[-1] if round_targets else alive_enemies[0].instance_id
                round_targets = round_targets + [last] * (multi - len(round_targets))

            player_actions_this_round = []
            enemy_actions_this_round = []
            state.log = []
            state._player_dodging = False

            for iid in state.initiative_order:
                if iid == "player":
                    for tgt in round_targets:
                        if not tgt:
                            tgt = alive_enemies[0].instance_id if alive_enemies else "unknown"
                        pa = self._resolve_player_action(
                            state, player, action_id, tgt, environment_actions
                        )
                        pa.round_num = state.round
                        state.log.append(pa)
                        state.full_log.append(pa)
                        player_actions_this_round.append({
                            "action_type": pa.action_type,
                            "target": pa.target,
                            "weapon": pa.weapon,
                            "roll": pa.roll,
                            "tier": pa.tier,
                            "damage": pa.damage,
                            "damage_type": getattr(pa, 'damage_type', '物理'),
                            "effects": [],
                        })
                        if state.finished:
                            break
                    if state.finished:
                        break
                    continue

                enemy = next((e for e in state.enemies if e.instance_id == iid), None)
                if not enemy or getattr(enemy, 'status', '') in ('dead', 'defeated') or getattr(enemy, 'hp', 1) <= 0:
                    continue

                multi = getattr(enemy, 'multi_attack', 1)
                for _ in range(multi):
                    ea = self._resolve_enemy_action(state, enemy, player)
                    ea.round_num = state.round
                    state.log.append(ea)
                    state.full_log.append(ea)
                    enemy_actions_this_round.append({
                        "actor": ea.actor,
                        "action_type": ea.action_type,
                        "roll": ea.roll,
                        "tier": ea.tier,
                        "damage": ea.damage,
                        "damage_type": getattr(ea, 'damage_type', '物理'),
                        "effects": [],
                    })
                    if state.player_hp <= 0:
                        state.finished = True
                        break
                if state.finished:
                    break

            rresult = self._build_round_result(
                state, player_actions_this_round, enemy_actions_this_round, state.round
            )

            if needs_llm:
                boss_phase = state._boss_current_phase or ""
                snapshot = self._build_battle_snapshot(state, player, boss_phase)
                rresult = self._llm_correct_round(
                    rresult, combat_init, state.enemies,
                    player_extra, snapshot, boss_phase, player_actions_this_round
                )
                corr_narr = rresult.get("narrative", "")
                if corr_narr:
                    state._correction_log.append(f"第{state.round}轮玩家修正: {corr_narr}")

                # ── 敌人 LLM 修正：每个有 special_rules 的敌人独立调用 ──
                inv_context = getattr(player, 'personal_description', '') or ''
                if getattr(player, 'extra', ''):
                    inv_context = (inv_context + '\n' + player.extra).strip()
                for ea_data in enemy_actions_this_round:
                    old_dmg = ea_data.get("damage", 0)
                    if old_dmg <= 0:
                        continue
                    enemy_id = ea_data.get("actor", "")
                    enemy = next((e for e in state.enemies
                                 if getattr(e, 'instance_id', '') == enemy_id), None)
                    if enemy and getattr(enemy, 'special_rules', ''):
                        corrected = self._llm_correct_enemy_round(
                            enemy, ea_data, player, player_extra, inv_context
                        )
                        new_dmg = max(0, corrected.get("damage", old_dmg))
                        state.player_hp = max(0, state.player_hp + old_dmg - new_dmg)
                        ea_data["damage"] = new_dmg
                        if corrected.get("narrative"):
                            ea_data["effects"] = ea_data.get("effects", []) + [corrected["narrative"]]
                            state._correction_log.append(f"第{state.round}轮{enemy_id}修正: {corrected['narrative']}")

            # 玩家伤害结算 — 每击独立应用
            for pa in player_actions_this_round:
                if pa.get("action_type") != "attack":
                    continue
                dmg = pa.get("damage", 0)
                tgt_iid = pa.get("target", "")
                enemy = next((e for e in state.enemies if getattr(e, 'instance_id', '') == tgt_iid), None)
                if not enemy:
                    continue
                # LLM 修正后的伤害优先，int() 防 None/str
                corrected_dmg = rresult.get("player_damage", 0)
                try:
                    effective = max(0, int(corrected_dmg if corrected_dmg is not None else dmg))
                except (ValueError, TypeError):
                    effective = max(0, int(dmg) if dmg else 0)
                enemy.hp = max(0, getattr(enemy, 'hp', 10) - effective)

            for enemy in state.enemies:
                if getattr(enemy, 'hp', 1) <= 0 or getattr(enemy, 'status', '') in ('dead', 'defeated'):
                    continue
                triggered = self._check_phase(state, enemy)
                if triggered:
                    desc = self._apply_phase(state, enemy, triggered, getattr(enemy, 'phases', []))
                    if desc:
                        rresult.setdefault("status_changes", []).append({
                            "entity_id": enemy.instance_id,
                            "field": "phase",
                            "old": "",
                            "new": triggered,
                        })

            round_log.append(rresult)

            alive_after = [e for e in state.enemies
                          if getattr(e, 'hp', 1) > 0 and getattr(e, 'status', '') != 'dead']
            if not alive_after:
                state.finished = True

            state.round += 1

        outcome = "win"
        if state.player_hp <= 0:
            outcome = "loss"
        elif state.round > max_rounds:
            outcome = "draw"

        combat_narrative = self._generate_combat_narrative(
            state, combat_init.player, combat_init.scene
        )

        return CombatResult(
            outcome=outcome,
            defeated_instance_ids=[],
            player_hp=state.player_hp,
            player_san=state.player_san,
            rounds=state.round,
            narrative=combat_narrative,
            round_log=round_log,
        )

    def run_single_round(self, combat_init: CombatInit, state: CombatState,
                         action_id: str, target_ids: list[str],
                         player_extra: str = "") -> dict:
        """Execute one combat round interactively. Returns result dict.

        Caller provides the current CombatState (with live HP/initiative/etc.).
        We execute one round and return the updated state metadata.
        """
        player = combat_init.player
        environment_actions = getattr(combat_init, 'environment_actions', [])
        available = self._get_player_actions(player, environment_actions)

        # Resolve action
        if not action_id or not any(a["id"] == action_id for a in available):
            action_id = "punch"

        alive_enemies = [e for e in state.enemies
                        if getattr(e, 'hp', 1) > 0 and getattr(e, 'status', '') not in ('dead', 'defeated')]
        if not alive_enemies:
            state.finished = True
            return self._build_single_round_result(state, combat_init)

        # Multi-attack target expansion
        match = next((a for a in available if a["id"] == action_id), None)
        multi = match.get("multi_attack", 1) if match else 1
        round_targets = list(target_ids) if target_ids else [alive_enemies[0].instance_id]
        if multi > len(round_targets):
            last = round_targets[-1] if round_targets else alive_enemies[0].instance_id
            round_targets = round_targets + [last] * (multi - len(round_targets))

        state.log = []
        state._player_dodging = False
        player_actions_this_round = []
        enemy_actions_this_round = []

        for iid in state.initiative_order:
            if iid == "player":
                for tgt in round_targets:
                    if not tgt:
                        tgt = alive_enemies[0].instance_id if alive_enemies else "unknown"
                    pa = self._resolve_player_action(state, player, action_id, tgt, environment_actions)
                    pa.round_num = state.round
                    state.log.append(pa)
                    state.full_log.append(pa)
                    player_actions_this_round.append({
                        "action_type": pa.action_type,
                        "target": pa.target,
                        "weapon": pa.weapon,
                        "roll": pa.roll,
                        "tier": pa.tier,
                        "damage": pa.damage,
                        "damage_type": getattr(pa, 'damage_type', '物理'),
                        "effects": [],
                    })
                    if state.finished:
                        break
                if state.finished:
                    break
                continue

            enemy = next((e for e in state.enemies if e.instance_id == iid), None)
            if not enemy or getattr(enemy, 'status', '') in ('dead', 'defeated') or getattr(enemy, 'hp', 1) <= 0:
                continue

            multi_e = getattr(enemy, 'multi_attack', 1)
            for _ in range(multi_e):
                ea = self._resolve_enemy_action(state, enemy, player)
                ea.round_num = state.round
                state.log.append(ea)
                state.full_log.append(ea)
                enemy_actions_this_round.append({
                    "actor": ea.actor,
                    "action_type": ea.action_type,
                    "roll": ea.roll,
                    "tier": ea.tier,
                    "damage": ea.damage,
                    "damage_type": getattr(ea, 'damage_type', '物理'),
                    "effects": [],
                })
                if state.player_hp <= 0:
                    state.finished = True
                    break
            if state.finished:
                break

        rresult = self._build_round_result(
            state, player_actions_this_round, enemy_actions_this_round, state.round
        )

        needs_llm = self._any_special_rules(combat_init, state.enemies)
        if needs_llm:
            boss_phase = state._boss_current_phase or ""
            snapshot = self._build_battle_snapshot(state, player, boss_phase)
            rresult = self._llm_correct_round(
                rresult, combat_init, state.enemies,
                player_extra, snapshot, boss_phase, player_actions_this_round
            )
            corr_narr = rresult.get("narrative", "")
            if corr_narr:
                state._correction_log.append(f"第{state.round}轮玩家修正: {corr_narr}")

            inv_context = getattr(player, 'personal_description', '') or ''
            if getattr(player, 'extra', ''):
                inv_context = (inv_context + '\n' + player.extra).strip()
            for ea_data in enemy_actions_this_round:
                old_dmg = ea_data.get("damage", 0)
                if old_dmg <= 0:
                    continue
                enemy_id = ea_data.get("actor", "")
                enemy = next((e for e in state.enemies
                             if getattr(e, 'instance_id', '') == enemy_id), None)
                if enemy and getattr(enemy, 'special_rules', ''):
                    corrected = self._llm_correct_enemy_round(
                        enemy, ea_data, player, player_extra, inv_context)
                    new_dmg = max(0, corrected.get("damage", old_dmg))
                    state.player_hp = max(0, state.player_hp + old_dmg - new_dmg)
                    ea_data["damage"] = new_dmg
                    if corrected.get("narrative"):
                        ea_data["effects"] = ea_data.get("effects", []) + [corrected["narrative"]]
                        state._correction_log.append(f"第{state.round}轮{enemy_id}修正: {corrected['narrative']}")

        # Apply player damage to enemies
        for pa in player_actions_this_round:
            if pa.get("action_type") != "attack":
                continue
            dmg = pa.get("damage", 0)
            tgt_iid = pa.get("target", "")
            enemy = next((e for e in state.enemies if getattr(e, 'instance_id', '') == tgt_iid), None)
            if not enemy:
                continue
            corrected_dmg = rresult.get("player_damage", 0)
            try:
                effective = max(0, int(corrected_dmg if corrected_dmg is not None else dmg))
            except (ValueError, TypeError):
                effective = max(0, int(dmg) if dmg else 0)
            enemy.hp = max(0, getattr(enemy, 'hp', 10) - effective)

        # Phase check
        for enemy in state.enemies:
            if getattr(enemy, 'hp', 1) <= 0 or getattr(enemy, 'status', '') == 'dead':
                continue
            triggered = self._check_phase(state, enemy)
            if triggered:
                desc = self._apply_phase(state, enemy, triggered, getattr(enemy, 'phases', []))
                if desc:
                    rresult.setdefault("status_changes", []).append({
                        "entity_id": enemy.instance_id,
                        "field": "phase",
                        "old": "",
                        "new": triggered,
                    })

        # Check end conditions
        alive_after = [e for e in state.enemies
                      if getattr(e, 'hp', 1) > 0 and getattr(e, 'status', '') != 'dead']
        if not alive_after:
            state.finished = True
        if state.player_hp <= 0:
            state.finished = True

        state.round += 1
        return self._build_single_round_result(state, combat_init)

    def _build_single_round_result(self, state: CombatState, combat_init) -> dict:
        """Build result dict after a single round."""
        is_boss = any(getattr(e, 'boss_mechanics', '') for e in state.enemies)
        outcome = None
        game_over = False

        if state.finished:
            player_fled = any(
                a.actor == "player" and a.action_type == "flee" and a.success
                for a in state.full_log
            )
            if player_fled:
                outcome = "flee"
            elif state.player_hp <= 0:
                outcome = "loss"
                game_over = not is_boss
            elif state.round > 20:
                outcome = "draw"
            else:
                outcome = "win"

        # Build concise round narrative
        lines = []
        for a in state.log:
            actor = "调查员" if a.actor == "player" else a.actor
            if a.action_type == "attack":
                s = "命中" if a.success else "未命中"
                dmg = f" 造成{a.damage}点伤害" if a.success and a.damage > 0 else ""
                lines.append(f"{actor} | {a.weapon} D100={a.roll} {s}{dmg}")
            elif a.action_type == "flee":
                lines.append(f"{actor} | 逃跑 {'成功' if a.success else '失败'}")
            elif a.action_type == "dodge":
                lines.append(f"{actor} | 回避")
            elif a.action_type in ("conceal", "aim", "charge"):
                lines.append(f"{actor} | {a.action_type}")
        round_narrative = "\n".join(lines)

        return {
            "finished": state.finished,
            "outcome": outcome,
            "player_hp": state.player_hp,
            "player_hp_max": state.player_hp_max,
            "player_san": state.player_san,
            "enemies": state.enemies,
            "round_log": state.log,
            "round_narrative": round_narrative,
            "is_boss": is_boss,
            "game_over": game_over,
            "round": state.round,
        }

    def _generate_combat_narrative(self, state, player, scene: str, log_dir: str = "") -> str:
        """Generate LLM combat summary from full round log."""
        if not state.full_log:
            return ""
        import json as _json, os as _os
        try:
            from llm import call_deepseek
            from config_llm import LLM_FLASH_MODEL
            from datetime import datetime

            log_lines = []
            enemies_desc = []
            for e in state.enemies:
                name = getattr(e, 'enemy_ref', getattr(e, 'name', '未知'))
                desc = getattr(e, 'description', '')
                enemies_desc.append(f"{name}" + (f"（{desc}）" if desc else ""))

            for a in state.full_log:
                hp_info = f" HP{a.hp_before}→{a.hp_after}" if a.damage > 0 else ""
                actor = "调查员" if a.actor == "player" else a.actor
                log_lines.append(
                    f"第{a.round_num}轮 {actor} {a.action_type}"
                    f"({a.skill_name}={a.skill_value} D100={a.roll} {a.tier})"
                    f" 伤害{a.damage}{hp_info}"
                )

            player_name = getattr(player, 'name', '调查员') if player else '调查员'
            player_desc = getattr(player, 'personal_description', '') or "" if player else ""
            prompt = f"""你是TRPG战斗叙事者。根据以下战斗记录生成一段简洁的摘要。

【场景】{scene}
【调查员】{player_name}{f' —— {player_desc}' if player_desc else ''}
【敌人】
{chr(10).join(f'  - {d}' for d in enemies_desc)}

【战斗日志】
{chr(10).join(log_lines)}

【LLM修正记录】
{chr(10).join(state._correction_log) if state._correction_log else '（无修正）'}

【最终结果】
调查员 HP: {state.player_hp}, SAN: {state.player_san}
敌人: {', '.join(f'{getattr(e, "enemy_ref", getattr(e, "name", "?"))} HP:{getattr(e, "hp", 0)}' for e in state.enemies)}
结果: {state.finished and ('玩家胜利' if all(getattr(e, 'hp', 0) <= 0 for e in state.enemies) else '玩家败北') or '未结束'}

返回 JSON：
{{"summary": "战斗摘要（中文≤120字），包含关键回合和最终结果"}}
直接输出 JSON。"""

            response = call_deepseek(
                prompt, json_mode=True, model=LLM_FLASH_MODEL,
                _label="combat_narrative",
                system="你是TRPG战斗叙事者，简洁概述战斗过程。",
                fallback_schema={"summary": ""},
            )

            _show_prompt("Combat Narrative", prompt,
                system="你是TRPG战斗叙事者，简洁概述战斗过程。")

            # 保存 LLM prompt + response（仅在显式传入 log_dir 时写入文件）
            if log_dir:
                try:
                    _os.makedirs(log_dir, exist_ok=True)
                    ts = datetime.now().strftime("%H%M%S")
                    prompt_path = f"{log_dir}/combat_narrative_{ts}_prompt.txt"
                    resp_path = f"{log_dir}/combat_narrative_{ts}_response.txt"
                    with open(prompt_path, 'w', encoding='utf-8') as f:
                        f.write(prompt)
                    with open(resp_path, 'w', encoding='utf-8') as f:
                        f.write(str(response))
                except Exception:
                    pass

            data = _json.loads(response) if isinstance(response, str) else response
            return data.get("summary", "") or ""
        except Exception:
            return ""

    # ── Init ──

    def _init_combat(self, combat_init: CombatInit) -> CombatState:
        """Set up combat state from CombatInit. Initiative by DEX descending.
        
        群组展开：quantity > 1 的 EnemyInstance 拆为独立战斗实体，分别计算 HP 和先攻。
        """
        import copy
        player = combat_init.player
        expanded_enemies = []
        for e in combat_init.enemies:
            qty = max(1, getattr(e, 'quantity', 1))
            per_hp = max(1, getattr(e, 'hp', 10) // qty)
            for i in range(qty):
                ce = copy.copy(e)
                ce.instance_id = f"{e.instance_id}_c{i}"
                ce.hp = per_hp
                ce.hp_max = per_hp
                ce.quantity = 1
                expanded_enemies.append(ce)
        state = CombatState(
            enemies=expanded_enemies,
            player_hp=player.derived.HP,
            player_hp_max=player.derived.HP,
            player_san=player.derived.SAN,
        )

        # Build initiative order: (actor_id, DEX)
        order = [("player", player.stats.DEX if hasattr(player, 'stats') else 50)]
        for enemy in expanded_enemies:
            dex = 50
            if hasattr(enemy, 'attributes'):
                dex = enemy.attributes.get("DEX", 50)
            elif hasattr(enemy, 'dex'):
                dex = enemy.dex
            order.append((enemy.instance_id, dex))
        order.sort(key=lambda x: -x[1])
        state.initiative_order = [oid for oid, _ in order]

        first_actor = state.initiative_order[0]
        state.is_player_turn = (first_actor == "player")
        for e in expanded_enemies:
            if getattr(e, 'boss_mechanics', ''):
                state._boss_hp_max = getattr(e, 'hp', state.player_hp)
                break
        for e in state.enemies:
            if not hasattr(e, 'hp_max') or not getattr(e, 'hp_max', 0):
                e.hp_max = getattr(e, 'hp', 10)
        return state

    def _match_action(self, raw_input: str, available: list[dict]) -> str:
        """Match raw player input to an available combat action id."""
        if not raw_input:
            return "punch"
        text = raw_input.lower()

        # Check each available action's label against player input
        for a in available:
            label = a["label"].lower()
            if label and label in text:
                return a["id"]

        # Keyword matching for fixed actions
        if any(kw in text for kw in ("拳", "打", "punch")):
            return "punch"
        if any(kw in text for kw in ("踢", "脚", "kick")):
            return "kick"
        if any(kw in text for kw in ("闪", "躲", "回避", "dodge")):
            return "dodge"
        if any(kw in text for kw in ("逃", "跑", "flee")):
            return "flee"
        if any(kw in text for kw in ("隐蔽", "潜行", "潜入", "conceal", "hide")):
            return "conceal"
        if any(kw in text for kw in ("瞄准", "aim")):
            return "aim"
        if any(kw in text for kw in ("蓄力", "charge")):
            return "charge"

        return "punch"

    # ── Player actions ──

    def _get_player_actions(self, player, environment_actions: list[dict] | None = None) -> list[dict]:
        """Build fixed action list from player skills and weapons, with optional environment interactions."""
        actions = [
            {"id": "punch", "label": "拳击", "skill": "格斗(拳)", "damage": "1D3+DB",
             "value": self._skill_value(player, "格斗(拳)")},
            {"id": "kick", "label": "踢击", "skill": "格斗(脚)", "damage": "1D6+DB",
             "value": self._skill_value(player, "格斗(脚)")},
            {"id": "dodge", "label": "回避", "skill": "回避",
             "value": self._skill_value(player, "回避"), "damage": None},
            {"id": "flee", "label": "逃跑", "skill": None, "value": None, "damage": None},
            {"id": "conceal", "label": "隐蔽", "skill": "潜行",
             "value": self._skill_value(player, "潜行"), "damage": None},
            {"id": "aim", "label": "瞄准", "skill": None,
             "value": None, "damage": None},
            {"id": "charge", "label": "蓄力", "skill": None,
             "value": None, "damage": None},
        ]
        for w in getattr(player, 'weapons', []):
            weapon_skill = getattr(w, 'skill_name', '') or getattr(w, 'skill_used', '')
            skill_val = self._skill_value(player, weapon_skill)
            actions.append({
                "id": f"weapon:{w.name}", "label": w.name,
                "skill": weapon_skill, "damage": w.damage,
                "value": skill_val,
                "damage_type": getattr(w, 'damage_type', '物理'),
                "armor_piercing": getattr(w, 'armor_piercing', 0),
                "attack_bonus": getattr(w, 'attack_bonus', 0),
                "multi_attack": getattr(w, 'multi_attack', 1),
            })
        if environment_actions:
            for ea in environment_actions:
                skill = ea.get("skill", "")
                skill_value = self._skill_value(player, skill) if skill else 50
                actions.append({
                    "id": f"env:{ea['id']}", "label": ea.get("label", ea["id"]),
                    "skill": skill, "damage": ea.get("damage"),
                    "value": skill_value,
                })
        return actions

    def _skill_value(self, player, skill_name: str) -> int:
        """Get player skill value, defaulting to STAT/2 for untrained combat skills."""
        skill = player.get_skill(skill_name)
        if skill:
            return skill.value
        if hasattr(player, 'stats'):
            if "回避" in skill_name:
                return max(1, player.stats.DEX // 2)
            return max(1, player.stats.STR // 2)
        return 25

    def _resolve_player_action(self, state, player, action_id: str,
                               target_iid: str, environment_actions: list[dict] | None = None) -> CombatAction:
        """Execute player's chosen action. Returns CombatAction record."""
        action = CombatAction(actor="player")

        if action_id == "dodge":
            action.action_type = "dodge"
            action.success = True
            action.narrative = "你摆出防御姿态，准备闪避攻击。"
            state._player_dodging = True
            return action

        if action_id == "flee":
            action.action_type = "flee"
            enemy_dex = max(
                (e.attributes.get("DEX", 50) if hasattr(e, 'attributes') else 50)
                for e in state.enemies if getattr(e, 'status', '') != 'dead'
            )
            player_dex = player.stats.DEX if hasattr(player, 'stats') else 50
            action.skill_name = "DEX对抗"
            action.skill_value = player_dex
            action.roll = random.randint(1, 100)
            action.success = action.roll <= player_dex and action.roll < enemy_dex
            action.tier = self._get_tier(action.roll, player_dex) if action.success else "failure"
            action.narrative = ("你抓住机会逃出了战斗！" if action.success
                              else "你试图逃跑但被敌人拦住了去路。")
            if action.success:
                state.finished = True
            return action

        if action_id == "conceal":
            action.action_type = "conceal"
            action.skill_name = "潜行"
            action.skill_value = self._skill_value(player, "潜行")
            action.roll = random.randint(1, 100)
            action.success = action.roll <= action.skill_value
            action.tier = self._get_tier(action.roll, action.skill_value) if action.success else "failure"
            if action.success:
                state._player_concealed = True
                action.narrative = "你隐蔽在阴影中，下次攻击获得优势。"
            else:
                action.narrative = "你试图藏匿但暴露了位置。"
            return action

        if action_id == "aim":
            action.action_type = "aim"
            action.success = True
            state._player_aiming = True
            action.narrative = "你专注瞄准，下次攻击命中率提升。"
            return action

        if action_id == "charge":
            action.action_type = "charge"
            action.success = True
            state._player_charged = True
            action.narrative = "你蓄势待发，下次攻击伤害提升。"
            return action

        # Attack actions
        actions = self._get_player_actions(player, environment_actions)
        match = next((a for a in actions if a["id"] == action_id), None)
        if not match:
            action.narrative = "未知动作。"
            return action

        action.action_type = "attack"
        action.weapon = match["label"]
        action.skill_name = match["skill"]
        action.skill_value = match["value"]
        action.roll = random.randint(1, 100)
        effective_skill = action.skill_value
        if match.get("attack_bonus"):
            effective_skill += match["attack_bonus"]
        if getattr(state, '_player_aiming', False):
            effective_skill += 20
            state._player_aiming = False
        if getattr(state, '_player_concealed', False):
            effective_skill += 10
            state._player_concealed = False
        action.success = action.roll <= effective_skill
        action.tier = self._get_tier(action.roll, effective_skill) if action.success else "failure"

        if action.success:
            if match.get("damage") is not None:
                enemy = next((e for e in state.enemies if e.instance_id == target_iid), None)
                if enemy:
                    enemy_attrs = enemy.attributes if hasattr(enemy, 'attributes') else {}
                    en_str = enemy_attrs.get("STR", 50)
                    en_siz = enemy_attrs.get("SIZ", 50)
                    damage = _roll_damage(match["damage"], en_str, en_siz)
                    armor = getattr(enemy, 'armor', '') or ''
                    armor_val = 0
                    if armor:
                        m_armor = re.search(r"(\d+)", armor)
                        armor_val = int(m_armor.group(1)) if m_armor else 0
                    ap = match.get("armor_piercing", 0)
                    effective_armor_val = max(0, armor_val - ap)
                    final_damage = max(0, damage - effective_armor_val)
                    dm_type = match.get("damage_type", "物理")
                    multipliers = getattr(enemy, 'damage_multipliers', {})
                    final_damage = _apply_damage_multiplier(final_damage, dm_type, multipliers)
                    if getattr(state, '_player_charged', False):
                        final_damage = int(final_damage * 1.5)
                        state._player_charged = False
                    action.damage = final_damage
                    action.hp_before = getattr(enemy, 'hp', 10)
                    if not hasattr(enemy, 'hp'):
                        enemy.hp = max(1, en_siz // 5)
                        action.hp_before = enemy.hp
                    action.hp_after = action.hp_before - final_damage
                    action.target = target_iid
                    action.narrative = f"你的{match['label']}命中！造成{final_damage}点伤害。"
            else:
                action.narrative = f"你成功地执行了{match['label']}！"
        else:
            action.narrative = f"你的{match['label']}未能命中目标。"

        return action

    def _get_tier(self, roll: int, skill_value: int) -> str:
        """Determine COC 7th success tier from D100 roll vs skill value."""
        if roll == 1:
            return "extreme"
        if roll <= max(1, skill_value // 5):
            return "extreme"
        if roll <= max(1, skill_value // 2):
            return "hard"
        return "regular"

    # ── Enemy actions ──

    def _select_enemy_attack(self, enemy) -> dict:
        """Weight-based attack selection from enemy attack list."""
        attacks = enemy.attacks if hasattr(enemy, 'attacks') else []
        if not attacks:
            return {"name": "攻击", "damage": {"dice_n": 1, "dice_d": 3, "bonus": 0, "use_db": False}, "weight": 1}
        weights = [getattr(a, "weight", 1) for a in attacks]
        return random.choices(attacks, weights=weights, k=1)[0]

    def _select_enemy_target(self, state, enemy) -> str:
        """Enemy targets player (extendable to NPCs later)."""
        return "player"

    def _resolve_enemy_action(self, state, enemy, player) -> CombatAction:
        """Rule-driven enemy action. Boss flag changes label text only."""
        is_boss = "boss" in getattr(enemy, 'flags', [])
        enemy_label = getattr(enemy, 'enemy_ref', 'Boss' if is_boss else '敌人')

        attack = self._select_enemy_attack(enemy)
        attack_name = attack.get("name", "攻击") if isinstance(attack, dict) else getattr(attack, "name", "攻击")
        action = CombatAction(
            actor=enemy.instance_id,
            action_type="attack",
            weapon=attack_name,
            skill_name=attack_name,
            target="player",
        )

        enemy_attrs = enemy.attributes if hasattr(enemy, 'attributes') else {}
        dodge_bonus = getattr(enemy, 'dodge_bonus', 0)
        enemy_skill = (enemy_attrs.get("DEX", 50) + enemy_attrs.get("POW", 50)) // 2 + dodge_bonus
        action.skill_value = enemy_skill
        action.roll = random.randint(1, 100)

        if getattr(state, '_player_dodging', False):
            action.success = False
            action.narrative = f"{enemy_label}的{attack_name}被你闪开了。"
            state._player_dodging = False
            return action

        action.success = action.roll <= enemy_skill
        action.tier = self._get_tier(action.roll, enemy_skill) if action.success else "failure"

        if action.success:
            en_str = enemy_attrs.get("STR", 50)
            en_siz = enemy_attrs.get("SIZ", 50)
            damage_formula = attack.get("damage", {"dice_n": 1, "dice_d": 3, "bonus": 0, "use_db": False}) if isinstance(attack, dict) else getattr(attack, "damage", {"dice_n": 1, "dice_d": 3, "bonus": 0, "use_db": False})
            damage = _roll_damage(damage_formula, en_str, en_siz)
            action.damage = damage
            action.hp_before = state.player_hp
            state.player_hp = max(0, state.player_hp - damage)
            action.hp_after = state.player_hp
            action.narrative = f"{enemy_label}用{attack_name}击中了你！造成{damage}点伤害。"
        else:
            action.narrative = f"{enemy_label}的{attack_name}未能命中你。"

        return action

    # ── Phase system ──

    def _check_phase(self, state, enemy) -> str | None:
        """Check if any phase triggers on this enemy. Returns phase name or None."""
        phases = getattr(enemy, 'phases', [])
        if not phases:
            return None
        current = getattr(enemy, '_current_phase', '')
        for ph in phases:
            trigger = ph.get("trigger", "") if isinstance(ph, dict) else getattr(ph, "trigger", "")
            name = ph.get("name", "") if isinstance(ph, dict) else getattr(ph, "name", "")
            if name == current:
                continue
            if trigger.startswith("hp_below_pct:"):
                pct = float(trigger.split(":", 1)[1])
                enemy_hp_max = getattr(enemy, 'hp_max', 10)
                if enemy_hp_max <= 0:
                    enemy_hp_max = 1
                if getattr(enemy, 'hp', 0) / enemy_hp_max <= pct:
                    return name
            elif trigger.startswith("round:"):
                target_round = int(trigger.split(":", 1)[1])
                if state.round >= target_round:
                    return name
        return None

    def _apply_phase(self, state, enemy, phase_name: str, phases: list) -> str:
        """Apply phase overrides to enemy. Returns narration string."""
        for ph in phases:
            if isinstance(ph, dict):
                p_name = ph.get("name", "")
                overrides = ph.get("overrides", {})
                description = ph.get("description", "")
            else:
                p_name = getattr(ph, "name", "")
                overrides = getattr(ph, "overrides", {})
                description = getattr(ph, "description", "")
            if p_name == phase_name:
                for field, value in overrides.items():
                    setattr(enemy, field, value)
                enemy._current_phase = phase_name
                state._boss_current_phase = phase_name
                return description
        return ""

    # ── LLM correction gate helpers ──

    def _any_special_rules(self, combat_init, enemies) -> bool:
        """Check if any entity in combat has non-empty special_rules."""
        for e in enemies:
            if getattr(e, 'special_rules', ''):
                return True
        for w in getattr(combat_init.player, 'weapons', []):
            if getattr(w, 'special_rules', ''):
                return True
        return False

    def _build_battle_snapshot(self, state, player, boss_phase: str = "") -> str:
        """Return <=500 char battle snapshot for LLM context."""
        lines = [
            f"第{state.round}轮",
            f"调查员 HP:{state.player_hp}/{state.player_hp_max} SAN:{state.player_san}",
        ]
        if boss_phase:
            lines.append(f"Boss当前阶段:{boss_phase}")
        for e in state.enemies:
            hp_max = getattr(e, 'hp_max', getattr(e, 'hp', 0))
            hp_pct = f"{getattr(e, 'hp', 0)}/{hp_max}" if hp_max else "?"
            phase = getattr(e, '_current_phase', '')
            phase_str = f" 阶段:{phase}" if phase else ""
            lines.append(
                f"[{e.instance_id}] {e.enemy_ref} HP:{hp_pct}"
                f" status:{getattr(e, 'status', '?')}{phase_str}"
            )
        return "\n".join(lines)

    def _build_round_result(self, state, player_actions: list, enemy_actions: list, round_num: int) -> dict:
        """Build RoundResult dict from this round's actions."""
        pa = player_actions[0] if player_actions else {}
        return {
            "round": round_num,
            "player_action": pa.get("action_type", ""),
            "player_target": pa.get("target", ""),
            "player_roll": pa.get("roll", 0),
            "player_tier": pa.get("tier", ""),
            "player_damage": pa.get("damage", 0),
            "player_damage_type": pa.get("damage_type", "物理"),
            "player_effects": pa.get("effects", []),
            "enemy_actions": [
                {
                    "enemy_id": ea.get("actor", ""),
                    "action": ea.get("action_type", ""),
                    "roll": ea.get("roll", 0),
                    "tier": ea.get("tier", ""),
                    "damage": ea.get("damage", 0),
                    "damage_type": ea.get("damage_type", "物理"),
                    "effects": ea.get("effects", []),
                }
                for ea in enemy_actions
            ],
            "status_changes": [],
            "narrative": "",
        }

    def _llm_correct_round(self, round_result: dict, combat_init, enemies,
                           player_extra: str, battle_snapshot: str,
                           boss_phase: str, player_actions: list = None) -> dict:
        """LLM 修正玩家回合伤害。自然语言输入，仅当前武器 special_rules。"""
        try:
            from llm import call_deepseek
            from config_llm import LLM_FLASH_MODEL
            import json as _json

            player_actions = player_actions or []
            player = combat_init.player

            # ── 调查员背景 ──
            inv_desc = getattr(player, 'personal_description', '') or ''
            if getattr(player, 'extra', ''):
                inv_desc = (inv_desc + '\n' + player.extra).strip()
            inv_name = getattr(player, 'name', '调查员')

            # ── 本轮所有攻击动作（支持 multi_attack） ──
            active_weapon_rules = ""
            active_weapon_name = ""
            attack_lines = []
            for i, pa in enumerate(player_actions):
                if pa.get("action_type") != "attack":
                    continue
                if not active_weapon_name and pa.get("weapon"):
                    active_weapon_name = pa["weapon"]
                    for w in getattr(player, 'weapons', []):
                        if getattr(w, 'name', '') == active_weapon_name:
                            active_weapon_rules = getattr(w, 'special_rules', '') or ''
                            break
                tgt = next((e for e in enemies if getattr(e, 'instance_id', '') == pa.get("target", "")), None)
                tgt_name = getattr(tgt, 'enemy_ref', pa.get("target", "?"))
                attack_lines.append(
                    f"第{i+1}击: {active_weapon_name or '基础攻击'} → {tgt_name}"
                    f" | D100={pa.get('roll', 0)} → {pa.get('tier', '')}"
                    f" | 原始伤害{pa.get('damage', 0)}（{pa.get('damage_type', '物理')}）"
                )
            if not attack_lines and player_actions:
                pa = player_actions[0]
                attack_lines.append(
                    f"动作: {pa.get('action_type', '?')}"
                    f" | D100={pa.get('roll', 0)} → {pa.get('tier', '')}"
                )

            # ── 目标敌人 ──
            target_iid = round_result.get("player_target", "")
            target_enemy = next((e for e in enemies if getattr(e, 'instance_id', '') == target_iid), None)

            lines = []
            if inv_desc:
                lines.append(f"【调查员背景】\n{inv_name}: {inv_desc}")
            extra = (player_extra or '').strip()
            if extra:
                lines.append(f"【本轮额外意图】\n{extra}\n（仅在有特殊规则且意图匹配时生效）")

            lines.append(f"玩家使用「{active_weapon_name or '基础攻击'}」发动攻击：")
            lines.extend(attack_lines)

            if active_weapon_rules:
                lines.append(f"\n【武器特殊规则】\n{active_weapon_name}: {active_weapon_rules}")

            if target_enemy:
                e = target_enemy
                hp = getattr(e, 'hp', 0)
                hp_max = getattr(e, 'hp_max', hp) or 1
                lines.append(f"\n【目标当前状态】")
                lines.append(f"{getattr(e, 'enemy_ref', '?')}: HP {hp}/{hp_max}")

            # 目标 + 在场所有敌人特殊规则
            all_sr = []
            for e in enemies:
                sr = getattr(e, 'special_rules', '') or ''
                if sr:
                    tag = "[Boss]" if getattr(e, 'boss_mechanics', '') else ""
                    same_target = (getattr(e, 'instance_id', '') == target_iid)
                    prefix = "→ " if same_target else ""
                    all_sr.append(f"{prefix}{getattr(e, 'enemy_ref', '?')}{tag}: {sr}")
            if all_sr:
                lines.append(f"\n【目标/在场敌人特殊规则】")
                lines.extend(all_sr)

            lines.append(f"\n【修正指令】")
            if active_weapon_rules or any(getattr(e, 'special_rules', '') for e in enemies):
                lines.append("根据上述特殊规则和额外意图，修正 player_damage 和 narrative。")
            else:
                lines.append("无特殊规则，原值返回。")
            lines.append("返回 JSON：{\"player_damage\": <int>, \"narrative\": \"<string>\"}")

            prompt_text = "\n".join(lines)
            _show_prompt("Combat Correct Round", prompt_text,
                system="你是 COC 7th 战斗裁判助理。根据武器/敌人特殊规则修正伤害值。narrative 用中文简述修正理由。")
            response = call_deepseek(
                prompt_text, json_mode=True, model=LLM_FLASH_MODEL,
                _label="combat_correct_round",
                system="你是 COC 7th 战斗裁判助理。根据武器/敌人特殊规则修正伤害值。narrative 用中文简述修正理由。",
                fallback_schema={"player_damage": round_result.get("player_damage", 0),
                                "narrative": round_result.get("narrative", "")},
            )
            data = _json.loads(response) if isinstance(response, str) else response
            corrected = dict(round_result)
            corrected["player_damage"] = int(data.get("player_damage", round_result.get("player_damage", 0)))
            corrected["narrative"] = data.get("narrative", round_result.get("narrative", ""))
            return corrected
        except Exception:
            return round_result

    def _llm_correct_enemy_round(self, enemy, action_data: dict, player,
                                 player_extra: str = "",
                                 investigator_context: str = "") -> dict:
        """LLM 修正敌人/Boss 攻击伤害。与玩家修正独立，可并行。"""
        try:
            from llm import call_deepseek
            from config_llm import LLM_FLASH_MODEL
            import json as _json

            enemy_name = getattr(enemy, 'enemy_ref', '敌人')
            atk_name = action_data.get("action_type", "攻击")
            roll = action_data.get("roll", 0)
            tier = action_data.get("tier", "")
            damage = action_data.get("damage", 0)
            dmg_type = action_data.get("damage_type", "物理")
            enemy_rules = getattr(enemy, 'special_rules', '') or ''
            inv_name = getattr(player, 'name', '调查员')

            lines = []
            if investigator_context:
                lines.append(f"【调查员背景】\n{inv_name}: {investigator_context}")
            extra = (player_extra or '').strip()
            if extra:
                lines.append(f"【本轮额外意图】\n{extra}\n（可能影响敌人攻击效果）")

            lines.append(f"{enemy_name}使用「{atk_name}」攻击{inv_name}")
            lines.append(f"D100={roll} → {tier}")
            lines.append(f"原始伤害值: {damage}（{dmg_type}）")

            if enemy_rules:
                lines.append(f"\n【敌人特殊规则】\n{enemy_name}: {enemy_rules}")

            if investigator_context:
                lines.append(f"\n【调查员特质影响】\n若调查员背景中有关联属性，请据此调整伤害。")
                lines.append(f"（例如：对某类型攻击脆弱/抗性、心理创伤触发额外伤害等）")

            lines.append(f"\n【修正指令】")
            if enemy_rules:
                lines.append("根据敌人特殊规则和调查员特质，修正伤害值和叙事。")
            else:
                lines.append("无特殊规则，原值返回。")
            lines.append("返回 JSON：{\"damage\": <int>, \"narrative\": \"<string>\"}")

            prompt_text = "\n".join(lines)
            _show_prompt("Combat Correct Enemy", prompt_text,
                system="你是 COC 7th 战斗裁判助理。根据敌人特殊规则和调查员特质修正伤害。narrative 用中文简述修正理由。")
            response = call_deepseek(
                prompt_text, json_mode=True, model=LLM_FLASH_MODEL,
                _label="combat_correct_enemy",
                system="你是 COC 7th 战斗裁判助理。根据敌人特殊规则和调查员特质修正伤害。narrative 用中文简述修正理由。",
                fallback_schema={"damage": damage, "narrative": ""},
            )
            data = _json.loads(response) if isinstance(response, str) else response
            return {"damage": int(data.get("damage", damage)), "narrative": data.get("narrative", "")}
        except Exception:
            return {"damage": int(action_data.get("damage", 0)), "narrative": ""}
